Reinstate `csw_inspector_role`
We can't remove the provider from the config until we've removed the objects:

```
Error: Provider configuration not present

To work with
module.csw_inspector_role.module.csw_role.data.aws_caller_identity.current its
original provider configuration at module.csw_inspector_role.provider.aws is
required, but it has been removed. This occurs when a provider configuration
is removed while objects created by that provider still exist in the state.
Re-add the provider configuration to destroy
module.csw_inspector_role.module.csw_role.data.aws_caller_identity.current,
after which you can remove the provider configuration again.

```